interface CemComponentProp {
  name: string;
  type: string;
  required: boolean;
}

interface CemComponentEvent {
  name: string;
  type: string;
}

interface CemComponentSlot {
  name: string;
}

interface CemComponentDefinition {
  tagName: string;
  props: CemComponentProp[];
  events: CemComponentEvent[];
  slots: CemComponentSlot[];
}

interface CreateGeneratedOutputInput {
  projectId?: string;
  libraryName?: string;
  componentDefinitions?: CemComponentDefinition[];
  runtimeImports?: {
    /**
     * Import specifier for the Lit component library. When provided, the
     * generated SSR runtime will include this import so custom element classes
     * are registered before `@lit-labs/ssr` renders them server-side.
     */
    libraryImport?: string;
  };
  ssrAvailable?: boolean;
}

type CreateLitPlannedWritesOptions = CreateGeneratedOutputInput;

export function createLitPlannedWrites({
  projectId,
  libraryName,
  componentDefinitions,
  runtimeImports,
  ssrAvailable,
}: CreateLitPlannedWritesOptions): Array<{
  relativePath: string;
  content: string;
}> {
  const componentTags = (componentDefinitions ?? []).map(
    (componentDefinition) => componentDefinition.tagName,
  );

  const plannedWrites: Array<{ relativePath: string; content: string }> = [
    {
      relativePath: 'index.ts',
      content: renderGeneratedIndex(projectId, componentTags, ssrAvailable),
    },
  ];

  if (ssrAvailable === true) {
    plannedWrites.push(
      {
        relativePath: 'runtime.ts',
        content: renderRuntimeBarrelModule(projectId, true),
      },
      {
        relativePath: 'runtime-ssr.generated.ts',
        content: renderServerRuntimeModule(
          projectId,
          libraryName,
          runtimeImports?.libraryImport,
        ),
      },
    );
  } else {
    plannedWrites.push(
      {
        relativePath: 'runtime.ts',
        content: renderRuntimeBarrelModule(projectId, false),
      },
      {
        relativePath: 'runtime-csr.generated.ts',
        content: renderClientRuntimeModule(
          projectId,
          libraryName,
          runtimeImports?.libraryImport,
        ),
      },
    );
  }

  plannedWrites.push(
    ...componentTags.map((componentTag) => ({
      relativePath: renderComponentWrapperRelativePath(
        componentTag,
        ssrAvailable,
      ),
      content: renderComponentWrapper({
        projectId,
        libraryName,
        componentDefinition: normalizeComponentDefinition(
          componentTag,
          (componentDefinitions ?? []).find(
            (definition) => definition.tagName === componentTag,
          ),
        ),
        ssrAvailable,
      }),
    })),
  );

  return plannedWrites;
}

function renderGeneratedIndex(
  projectId: string | undefined,
  componentTags: string[],
  ssrAvailable?: boolean,
): string {
  const mode = ssrAvailable === true ? 'ssr' : 'csr';
  const exportLines = componentTags.map(
    (componentTag) =>
      `export { ${toWrapperName(componentTag)} } from './${componentTag}';`,
  );

  return [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId ?? 'unknown'}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
    `export const generatedComponentTags = ${JSON.stringify(componentTags)} as const;`,
    `export const generatedMode = '${mode}' as const;`,
    ...exportLines,
    '',
  ].join('\n');
}

function renderComponentWrapper(input: {
  projectId?: string;
  libraryName?: string;
  componentDefinition: CemComponentDefinition;
  ssrAvailable?: boolean;
}): string {
  const { projectId, libraryName, componentDefinition, ssrAvailable } = input;
  const { tagName: componentTag } = componentDefinition;
  const wrapperName = toWrapperName(componentTag);
  const ssrBridgeName = toBridgeComponentName(
    libraryName,
    'SSR',
    'GeneratedLitComponent',
  );
  const csrBridgeName = toBridgeComponentName(
    libraryName,
    'CSR',
    'GeneratedLitCSRComponent',
  );
  const bridgeName = ssrAvailable === true ? ssrBridgeName : csrBridgeName;
  const lines = [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId ?? 'unknown'}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
  ];

  lines.push('', "import { Slot, component$ } from '@builder.io/qwik';");

  if (componentDefinition.events.length > 0) {
    lines.push("import type { QRL } from '@builder.io/qwik';");
  }

  lines.push(`import { ${bridgeName} } from './runtime';`, '');

  const propsTypeName = `${wrapperName}Props`;
  const propLines = componentDefinition.props.map((prop) => {
    const key = isValidIdentifier(prop.name) ? prop.name : `'${prop.name}'`;
    const optionalToken = prop.required ? '' : '?';

    return `  ${key}${optionalToken}: ${prop.type};`;
  });

  const eventPropLines = componentDefinition.events.map(
    (event) =>
      `  ${toEventPropName(event.name)}?: QRL<(event: ${event.type}) => void>;`,
  );

  propLines.push(...eventPropLines, '  [key: string]: unknown;');

  const slotLines = [
    '      <Slot />',
    ...componentDefinition.slots.map(
      (slot) =>
        `      <span q:slot=${JSON.stringify(slot.name)} style={{ display: 'contents' }}>\n        <Slot name=${JSON.stringify(slot.name)} />\n      </span>`,
    ),
  ];
  const slotListToken =
    componentDefinition.slots.length > 0
      ? JSON.stringify(componentDefinition.slots.map((slot) => slot.name))
      : 'undefined';
  const splitPropsLines = [
    '  const isEventBindingKey = (key: string) =>',
    "    /^on[A-Z].*\\$$/.test(key) || key.includes(':');",
    '  const eventProps: Record<string, unknown> = {};',
    '  const elementProps: Record<string, unknown> = {};',
    '',
    '  for (const [key, value] of Object.entries(props as Record<string, unknown>)) {',
    "    if (key === 'children') {",
    '      continue;',
    '    }',
    '',
    '    if (isEventBindingKey(key)) {',
    '      eventProps[key] = value;',
    '      continue;',
    '    }',
    '',
    '    elementProps[key] = value;',
    '  }',
  ];

  const mappedEventLines =
    componentDefinition.events.length > 0
      ? [
          '',
          `  const mappedEventPropKeys = new Set(${JSON.stringify(componentDefinition.events.map((event) => toEventPropName(event.name)))});`,
          '  const passthroughEventProps = Object.fromEntries(',
          '    Object.entries(eventProps).filter(',
          '      ([key]) => !mappedEventPropKeys.has(key),',
          '    ),',
          '  );',
          '',
          '  const events: Record<string, QRL<(...args: any[]) => void>> = {};',
          ...componentDefinition.events.map(
            (event) =>
              `  if (props.${toEventPropName(event.name)}) { events['${event.name}'] = props.${toEventPropName(event.name)}; }`,
          ),
          '  const mappedEvents = Object.keys(events).length > 0 ? events : undefined;',
        ]
      : [
          '',
          '  const passthroughEventProps = eventProps;',
          '  const mappedEvents = undefined;',
        ];

  lines.push(
    `export interface ${propsTypeName} {`,
    ...propLines,
    '}',
    '',
    `export const ${wrapperName} = component$<${propsTypeName}>((props) => {`,
    ...splitPropsLines,
    ...mappedEventLines,
    '',
    '  return (',
    `    <${bridgeName}`,
    `      tagName=${JSON.stringify(componentTag)}`,
    '      props={elementProps}',
    '      events={mappedEvents}',
    `      slots={${slotListToken}}`,
    '      {...passthroughEventProps}',
    '    >',
    ...slotLines,
    `    </${bridgeName}>`,
    '  );',
    '});',
  );

  lines.push('');

  return lines.join('\n');
}

function renderComponentWrapperRelativePath(
  componentTag: string,
  _ssrAvailable: boolean | undefined,
): string {
  return `${componentTag}.tsx`;
}

function renderRuntimeBarrelModule(
  projectId: string | undefined,
  ssrAvailable: boolean,
): string {
  const runtimeExportLine = ssrAvailable
    ? "export * from './runtime-ssr.generated';"
    : "export * from './runtime-csr.generated';";

  return [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId ?? 'unknown'}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
    runtimeExportLine,
    '',
  ].join('\n');
}

function renderClientRuntimeModule(
  projectId: string | undefined,
  libraryName?: string,
  libraryImport?: string,
): string {
  const csrBridgeName = toBridgeComponentName(
    libraryName,
    'CSR',
    'GeneratedLitCSRComponent',
  );
  const clientSetupName = toCsrClientSetupHookName(libraryName);

  const hasLibraryImport =
    libraryImport !== undefined && libraryImport.trim().length > 0;

  const lines = [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId ?? 'unknown'}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
  ];

  if (hasLibraryImport) {
    lines.push("import { $ } from '@builder.io/qwik';");
    lines.push(
      `import { createLitCSRClientSetup, createLitCSRComponent } from '@qwik-custom-elements/adapter-lit/client';`,
    );
  } else {
    lines.push(
      "import { createLitCSRComponent } from '@qwik-custom-elements/adapter-lit/client';",
    );
  }

  if (hasLibraryImport) {
    lines.push(
      '',
      `const importLibrary = async (): Promise<void> => {`,
      `  await import('${libraryImport}');`,
      `};`,
      `const importLibraryQrl = $(importLibrary);`,
      `export const ${clientSetupName} = createLitCSRClientSetup(importLibraryQrl);`,
    );
  }

  lines.push(
    '',
    `export const ${csrBridgeName} = createLitCSRComponent();`,
    '',
  );

  return lines.join('\n');
}

function renderServerRuntimeModule(
  projectId: string | undefined,
  libraryName?: string,
  libraryImport?: string,
): string {
  const ssrBridgeName = toBridgeComponentName(
    libraryName,
    'SSR',
    'GeneratedLitComponent',
  );
  const clientSetupName = toClientSetupHookName(libraryName);

  const hasLibraryImport =
    libraryImport !== undefined && libraryImport.trim().length > 0;

  const lines = [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId ?? 'unknown'}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
  ];

  if (hasLibraryImport) {
    lines.push("import { $ } from '@builder.io/qwik';");
    lines.push(
      "import { createLitSSRClientSetup } from '@qwik-custom-elements/adapter-lit/client';",
    );
  }

  lines.push(
    "import { createLitSSRComponent } from '@qwik-custom-elements/adapter-lit/ssr';",
  );

  if (hasLibraryImport) {
    lines.push(
      `// Register Lit element classes for server-side rendering.`,
      `import '${libraryImport}';`,
      '',
      `const importLibrary = async (): Promise<void> => {`,
      `  await import('${libraryImport}');`,
      `};`,
      `const importLibraryQrl = $(importLibrary);`,
      `export const ${clientSetupName} = createLitSSRClientSetup(importLibraryQrl);`,
    );
  }

  lines.push(
    '',
    `export const ${ssrBridgeName} = createLitSSRComponent();`,
    '',
  );

  return lines.join('\n');
}

function toClientSetupHookName(libraryName: string | undefined): string {
  if (!libraryName || libraryName.trim().length === 0) {
    return 'useLitSSRClientSetup';
  }

  return `use${toPascalCase(libraryName)}SSRClientSetup`;
}

function toCsrClientSetupHookName(libraryName: string | undefined): string {
  if (!libraryName || libraryName.trim().length === 0) {
    return 'useLitCSRClientSetup';
  }

  return `use${toPascalCase(libraryName)}CSRClientSetup`;
}

function toPascalCase(name: string): string {
  return name
    .split(/[-_]/)
    .filter((p) => p.length > 0)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join('');
}

function isValidIdentifier(value: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value);
}

function toEventPropName(eventName: string): string {
  return `on${toPascalCase(eventName)}$`;
}

function normalizeComponentDefinition(
  componentTag: string,
  input: Partial<CemComponentDefinition> | undefined,
): CemComponentDefinition {
  return {
    tagName: input?.tagName ?? componentTag,
    props: input?.props ?? [],
    events: input?.events ?? [],
    slots: input?.slots ?? [],
  };
}

function toBridgeComponentName(
  libraryName: string | undefined,
  mode: 'SSR' | 'CSR',
  fallback: string,
): string {
  if (!libraryName || libraryName.trim().length === 0) {
    return fallback;
  }

  return `${toPascalCase(libraryName)}${mode}BridgeComponent`;
}

function toWrapperName(componentTag: string): string {
  const parts = componentTag.split('-').filter((part) => part.length > 0);
  const normalizedName = parts
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join('');

  return `Qwik${normalizedName}`;
}
