interface CemComponentDefinition {
  tagName: string;
}

interface CreateGeneratedOutputInput {
  projectId?: string;
  componentDefinitions?: CemComponentDefinition[];
  ssrAvailable?: boolean;
}

interface CreateLitPlannedWritesOptions extends CreateGeneratedOutputInput {
  renderComponentSsrHtml?: (options?: { tagName?: unknown }) => string | null;
}

export function createLitPlannedWrites({
  projectId,
  componentDefinitions,
  ssrAvailable,
  renderComponentSsrHtml,
}: CreateLitPlannedWritesOptions): Array<{
  relativePath: string;
  content: string;
}> {
  const componentTags = (componentDefinitions ?? []).map(
    (componentDefinition) => componentDefinition.tagName,
  );

  const plannedWrites: Array<{ relativePath: string; content: string }> = [
    {
      relativePath: 'index.ts',
      content: renderGeneratedIndex(projectId, componentTags),
    },
  ];

  if (ssrAvailable === true) {
    plannedWrites.push(
      {
        relativePath: 'runtime.ts',
        content: renderRuntimeBarrelModule(projectId, true),
      },
      {
        relativePath: 'runtime-ssr.generated.ts',
        content: renderServerRuntimeModule(projectId),
      },
    );
  } else {
    plannedWrites.push(
      {
        relativePath: 'runtime.ts',
        content: renderRuntimeBarrelModule(projectId, false),
      },
      {
        relativePath: 'runtime-csr.generated.ts',
        content: renderClientRuntimeModule(projectId),
      },
    );
  }

  plannedWrites.push(
    ...componentTags.map((componentTag) => ({
      relativePath: `${componentTag}.ts`,
      content: renderComponentWrapper({
        projectId,
        componentTag,
        ssrAvailable,
        ssrMarkup:
          ssrAvailable === true && renderComponentSsrHtml != null
            ? renderComponentSsrHtml({ tagName: componentTag })
            : null,
      }),
    })),
  );

  return plannedWrites;
}

function renderGeneratedIndex(
  projectId: string | undefined,
  componentTags: string[],
): string {
  const exportLines = componentTags.map(
    (componentTag) =>
      `export { ${toWrapperName(componentTag)} } from './${componentTag}';`,
  );

  return [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId ?? 'unknown'}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
    `export const generatedComponentTags = ${JSON.stringify(componentTags)} as const;`,
    ...exportLines,
    '',
  ].join('\n');
}

function renderComponentWrapper(input: {
  projectId?: string;
  componentTag: string;
  ssrAvailable?: boolean;
  ssrMarkup: string | null;
}): string {
  const { projectId, componentTag, ssrAvailable, ssrMarkup } = input;
  const wrapperName = toWrapperName(componentTag);
  const lines = [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId ?? 'unknown'}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
    `export const ${wrapperName} = ${JSON.stringify(componentTag)} as const;`,
  ];

  if (ssrAvailable === true) {
    lines.splice(
      3,
      0,
      "import { GeneratedLitComponent } from './runtime';",
      '',
    );
  } else {
    lines.splice(
      3,
      0,
      "import { GeneratedLitCSRComponent } from './runtime';",
      '',
    );
  }

  if (ssrMarkup != null) {
    lines.push(
      `export const ${wrapperName}SsrHtml = ${JSON.stringify(ssrMarkup)} as const;`,
    );

    if (ssrAvailable === true) {
      lines.push(
        `export const ${wrapperName}SsrHtmlFromBridge = GeneratedLitComponent({ tagName: ${JSON.stringify(componentTag)} });`,
      );
    }
  }

  if (ssrAvailable !== true) {
    lines.push(
      `export const ${wrapperName}CsrTagFromBridge = GeneratedLitCSRComponent({ tagName: ${JSON.stringify(componentTag)} });`,
    );
  }

  lines.push('');

  return lines.join('\n');
}

function renderRuntimeBarrelModule(
  projectId: string | undefined,
  ssrAvailable: boolean,
): string {
  const runtimeExportLine = ssrAvailable
    ? "export * from './runtime-ssr.generated';"
    : "export * from './runtime-csr.generated';";

  return [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId ?? 'unknown'}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
    runtimeExportLine,
    '',
  ].join('\n');
}

function renderClientRuntimeModule(projectId: string | undefined): string {
  return [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId ?? 'unknown'}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
    "import { createLitCSRComponent, renderComponentCsrTag } from '@qwik-custom-elements/adapter-lit/client';",
    '',
    'export const GeneratedLitCSRComponent = createLitCSRComponent(renderComponentCsrTag);',
    '',
  ].join('\n');
}

function renderServerRuntimeModule(projectId: string | undefined): string {
  return [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId ?? 'unknown'}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
    "import { createLitSSRComponent, renderComponentSsrHtml } from '@qwik-custom-elements/adapter-lit/ssr';",
    '',
    'export const GeneratedLitComponent = createLitSSRComponent(renderComponentSsrHtml);',
    '',
  ].join('\n');
}

function toWrapperName(componentTag: string): string {
  const parts = componentTag.split('-').filter((part) => part.length > 0);
  const normalizedName = parts
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join('');

  return `Qwik${normalizedName}`;
}
