interface CemComponentDefinition {
  tagName: string;
}

interface CreateGeneratedOutputInput {
  projectId?: string;
  componentDefinitions?: CemComponentDefinition[];
  ssrAvailable?: boolean;
}

interface CreateLitPlannedWritesOptions extends CreateGeneratedOutputInput {
  renderComponentSsrHtml?: (options?: { tagName?: unknown }) => string | null;
}

export function createLitPlannedWrites({
  projectId,
  componentDefinitions,
  ssrAvailable,
  renderComponentSsrHtml,
}: CreateLitPlannedWritesOptions): Array<{
  relativePath: string;
  content: string;
}> {
  const componentTags = (componentDefinitions ?? []).map(
    (componentDefinition) => componentDefinition.tagName,
  );

  return [
    {
      relativePath: 'index.ts',
      content: renderGeneratedIndex(projectId, componentTags),
    },
    ...componentTags.map((componentTag) => ({
      relativePath: `${componentTag}.ts`,
      content: renderComponentWrapper({
        projectId,
        componentTag,
        ssrMarkup:
          ssrAvailable === true && renderComponentSsrHtml != null
            ? renderComponentSsrHtml({ tagName: componentTag })
            : null,
      }),
    })),
  ];
}

function renderGeneratedIndex(
  projectId: string | undefined,
  componentTags: string[],
): string {
  const exportLines = componentTags.map(
    (componentTag) =>
      `export { ${toWrapperName(componentTag)} } from './${componentTag}';`,
  );

  return [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId ?? 'unknown'}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
    `export const generatedComponentTags = ${JSON.stringify(componentTags)} as const;`,
    ...exportLines,
    '',
  ].join('\n');
}

function renderComponentWrapper(input: {
  projectId?: string;
  componentTag: string;
  ssrMarkup: string | null;
}): string {
  const { projectId, componentTag, ssrMarkup } = input;
  const wrapperName = toWrapperName(componentTag);
  const lines = [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId ?? 'unknown'}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
    `export const ${wrapperName} = ${JSON.stringify(componentTag)} as const;`,
  ];

  if (ssrMarkup != null) {
    lines.push(
      `export const ${wrapperName}SsrHtml = ${JSON.stringify(ssrMarkup)} as const;`,
    );
  }

  lines.push('');

  return lines.join('\n');
}

function toWrapperName(componentTag: string): string {
  const parts = componentTag.split('-').filter((part) => part.length > 0);
  const normalizedName = parts
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join('');

  return `Qwik${normalizedName}`;
}
