import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import type {
  GenerateOptions,
  GenerationProjectResult,
  GenerationResult,
  GeneratorConfig,
  GeneratorProject,
} from './types.js';

export class GenerationError extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'GenerationError';
    this.code = code;
  }
}

export async function generateFromConfig(
  config: GeneratorConfig,
  options: GenerateOptions = {},
): Promise<GenerationResult> {
  const cwd = options.cwd ?? process.cwd();
  const sortedProjects = [...config.projects].sort((a, b) =>
    a.id.localeCompare(b.id),
  );

  if (sortedProjects.length !== 1) {
    throw new GenerationError(
      'QCE_GENERATION_UNSUPPORTED',
      'Current generator slice supports exactly one project.',
    );
  }

  const projectResults: GenerationProjectResult[] = [];

  for (const project of sortedProjects) {
    const result = await generateProject(project, cwd, config.dryRun === true);
    projectResults.push(result);
  }

  return {
    dryRun: config.dryRun === true,
    projects: projectResults,
  };
}

async function generateProject(
  project: GeneratorProject,
  cwd: string,
  dryRun: boolean,
): Promise<GenerationProjectResult> {
  const sourcePath = path.resolve(cwd, project.source);
  const outDirPath = path.resolve(cwd, project.outDir);
  const componentTags = await readComponentTagsFromCem(sourcePath);
  const plannedWrites = createPlannedWrites(project.id, outDirPath, componentTags);

  if (!dryRun) {
    await mkdir(outDirPath, { recursive: true });
    for (const plannedWrite of plannedWrites) {
      await writeFile(plannedWrite.path, plannedWrite.content, 'utf8');
    }
  }

  return {
    projectId: project.id,
    sourcePath,
    outDirPath,
    componentTags,
    plannedWrites,
    wroteFiles: !dryRun,
  };
}

function createPlannedWrites(
  projectId: string,
  outDirPath: string,
  componentTags: string[],
): Array<{ path: string; content: string }> {
  const wrapperWrites = componentTags.map((componentTag) => ({
    path: path.join(outDirPath, `${componentTag}.ts`),
    content: renderComponentWrapper(projectId, componentTag),
  }));

  return [
    {
      path: path.join(outDirPath, 'index.ts'),
      content: renderGeneratedIndex(projectId, componentTags),
    },
    ...wrapperWrites,
  ];
}

async function readComponentTagsFromCem(sourcePath: string): Promise<string[]> {
  let parsed: unknown;

  try {
    const rawText = await readFile(sourcePath, 'utf8');
    parsed = JSON.parse(rawText) as unknown;
  } catch (error) {
    throw new GenerationError(
      'QCE_CEM_READ_FAILED',
      `Could not read CEM source at ${sourcePath}: ${toErrorMessage(error)}`,
    );
  }

  const manifest = parsed as {
    modules?: Array<{ declarations?: Array<{ tagName?: unknown }> }>;
  };

  const tags = new Set<string>();

  for (const module of manifest.modules ?? []) {
    for (const declaration of module.declarations ?? []) {
      if (typeof declaration.tagName === 'string') {
        const normalizedTag = declaration.tagName.trim();
        if (normalizedTag) {
          tags.add(normalizedTag);
        }
      }
    }
  }

  return Array.from(tags).sort((a, b) => a.localeCompare(b));
}

function renderGeneratedIndex(projectId: string, componentTags: string[]): string {
  const exportLines = componentTags.map(
    (componentTag) =>
      `export { ${toWrapperName(componentTag)} } from './${componentTag}';`,
  );

  return [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
    `export const generatedComponentTags = ${JSON.stringify(componentTags)} as const;`,
    ...exportLines,
    '',
  ].join('\n');
}

function renderComponentWrapper(projectId: string, componentTag: string): string {
  return [
    `// Generated by @qwik-custom-elements/core. Project: ${projectId}.`,
    '// Do not edit this file directly. Use a manual extension layer.',
    '',
    `export const ${toWrapperName(componentTag)} = ${JSON.stringify(componentTag)} as const;`,
    '',
  ].join('\n');
}

function toWrapperName(componentTag: string): string {
  const parts = componentTag.split('-').filter((part) => part.length > 0);
  const normalizedName = parts
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join('');

  return `Qwik${normalizedName}`;
}

function toErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
