// Generated by @qwik-custom-elements/core. Project: demo-csr.
// Do not edit this file directly. Use a manual extension layer.

import { $ } from '@builder.io/qwik';
import { createStencilCSRComponent, createStencilClientSetup } from '@qwik-custom-elements/adapter-stencil/client';
import { defineCustomElements as runtimeDefineCustomElements } from '@qwik-custom-elements/test-stencil-lib/loader';

export const defineCustomElements = async (): Promise<void> => {
  await Promise.resolve(runtimeDefineCustomElements());
};

export const defineCustomElementsQrl = $(defineCustomElements);
export const useGeneratedStencilClientSetup =
  createStencilClientSetup(defineCustomElementsQrl);
export const GeneratedStencilCSRComponent = createStencilCSRComponent();
