import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import { GenerationError, generateFromConfig } from '../generator.js';
import type { GeneratorConfig } from '../types.js';

async function withTempDir(
  run: (tempDir: string) => Promise<void>,
): Promise<void> {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'qce-core-'));
  try {
    await run(tempDir);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

function createSingleProjectConfig(
  tempDir: string,
  dryRun = false,
): GeneratorConfig {
  return {
    dryRun,
    projects: [
      {
        id: 'demo',
        adapter: 'stencil',
        adapterPackage: '@qwik-custom-elements/adapter-stencil',
        source: './custom-elements.json',
        outDir: './src/generated',
      },
    ],
  };
}

describe('generateFromConfig', () => {
  it('produces deterministic planned writes in dry-run mode without mutating files', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify(
          {
            modules: [
              {
                declarations: [
                  { tagName: 'z-card' },
                  { tagName: 'a-button' },
                  { tagName: 'z-card' },
                ],
              },
            ],
          },
          null,
          2,
        ),
        'utf8',
      );

      const result = await generateFromConfig(
        createSingleProjectConfig(tempDir, true),
        { cwd: tempDir },
      );

      expect(result.dryRun).toBe(true);
      expect(result.projects).toHaveLength(1);
      expect(result.projects[0].wroteFiles).toBe(false);
      expect(result.projects[0].componentTags).toEqual(['a-button', 'z-card']);
      expect(result.projects[0].plannedWrites).toHaveLength(3);

      const indexWrite = result.projects[0].plannedWrites.find((plannedWrite) =>
        plannedWrite.path.endsWith(path.join('src', 'generated', 'index.ts')),
      );
      const buttonWrite = result.projects[0].plannedWrites.find(
        (plannedWrite) =>
          plannedWrite.path.endsWith(
            path.join('src', 'generated', 'a-button.ts'),
          ),
      );
      const cardWrite = result.projects[0].plannedWrites.find((plannedWrite) =>
        plannedWrite.path.endsWith(path.join('src', 'generated', 'z-card.ts')),
      );

      expect(indexWrite?.content).toContain(
        '// Generated by @qwik-custom-elements/core. Project: demo.',
      );
      expect(indexWrite?.content).toContain(
        'export const generatedComponentTags = ["a-button","z-card"] as const;',
      );
      expect(indexWrite?.content).toContain(
        "export { QwikAButton } from './a-button';",
      );
      expect(indexWrite?.content).toContain(
        "export { QwikZCard } from './z-card';",
      );
      expect(buttonWrite?.content).toContain(
        'export const QwikAButton = "a-button" as const;',
      );
      expect(cardWrite?.content).toContain(
        'export const QwikZCard = "z-card" as const;',
      );

      await expect(readFile(indexWrite!.path, 'utf8')).rejects.toThrow();
      await expect(readFile(buttonWrite!.path, 'utf8')).rejects.toThrow();
      await expect(readFile(cardWrite!.path, 'utf8')).rejects.toThrow();
    });
  });

  it('writes generated index.ts in non-dry-run mode', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify({
          modules: [{ declarations: [{ tagName: 'app-root' }] }],
        }),
        'utf8',
      );

      const result = await generateFromConfig(
        createSingleProjectConfig(tempDir),
        {
          cwd: tempDir,
        },
      );
      const indexWrite = result.projects[0].plannedWrites.find((plannedWrite) =>
        plannedWrite.path.endsWith(path.join('src', 'generated', 'index.ts')),
      );
      const wrapperWrite = result.projects[0].plannedWrites.find(
        (plannedWrite) =>
          plannedWrite.path.endsWith(
            path.join('src', 'generated', 'app-root.ts'),
          ),
      );
      const indexDiskContent = await readFile(indexWrite!.path, 'utf8');
      const wrapperDiskContent = await readFile(wrapperWrite!.path, 'utf8');

      expect(result.projects[0].wroteFiles).toBe(true);
      expect(result.projects[0].plannedWrites).toHaveLength(2);
      expect(indexDiskContent).toBe(indexWrite!.content);
      expect(wrapperDiskContent).toBe(wrapperWrite!.content);
    });
  });

  it('keeps generated files byte-stable across repeated write runs', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify(
          {
            modules: [
              {
                declarations: [
                  { tagName: 'card-panel' },
                  { tagName: 'app-root' },
                ],
              },
            ],
          },
          null,
          2,
        ),
        'utf8',
      );

      const config = createSingleProjectConfig(tempDir);
      const firstRun = await generateFromConfig(config, { cwd: tempDir });

      const firstIndexWrite = firstRun.projects[0].plannedWrites.find(
        (plannedWrite) =>
          plannedWrite.path.endsWith(path.join('src', 'generated', 'index.ts')),
      );
      const firstAppRootWrite = firstRun.projects[0].plannedWrites.find(
        (plannedWrite) =>
          plannedWrite.path.endsWith(
            path.join('src', 'generated', 'app-root.ts'),
          ),
      );
      const firstCardPanelWrite = firstRun.projects[0].plannedWrites.find(
        (plannedWrite) =>
          plannedWrite.path.endsWith(
            path.join('src', 'generated', 'card-panel.ts'),
          ),
      );

      const firstIndexDiskContent = await readFile(
        firstIndexWrite!.path,
        'utf8',
      );
      const firstAppRootDiskContent = await readFile(
        firstAppRootWrite!.path,
        'utf8',
      );
      const firstCardPanelDiskContent = await readFile(
        firstCardPanelWrite!.path,
        'utf8',
      );

      const secondRun = await generateFromConfig(config, { cwd: tempDir });
      const secondIndexWrite = secondRun.projects[0].plannedWrites.find(
        (plannedWrite) =>
          plannedWrite.path.endsWith(path.join('src', 'generated', 'index.ts')),
      );
      const secondAppRootWrite = secondRun.projects[0].plannedWrites.find(
        (plannedWrite) =>
          plannedWrite.path.endsWith(
            path.join('src', 'generated', 'app-root.ts'),
          ),
      );
      const secondCardPanelWrite = secondRun.projects[0].plannedWrites.find(
        (plannedWrite) =>
          plannedWrite.path.endsWith(
            path.join('src', 'generated', 'card-panel.ts'),
          ),
      );

      const secondIndexDiskContent = await readFile(
        secondIndexWrite!.path,
        'utf8',
      );
      const secondAppRootDiskContent = await readFile(
        secondAppRootWrite!.path,
        'utf8',
      );
      const secondCardPanelDiskContent = await readFile(
        secondCardPanelWrite!.path,
        'utf8',
      );

      expect(
        secondRun.projects[0].plannedWrites.map((write) => write.path),
      ).toEqual(firstRun.projects[0].plannedWrites.map((write) => write.path));
      expect(secondIndexWrite!.content).toBe(firstIndexWrite!.content);
      expect(secondAppRootWrite!.content).toBe(firstAppRootWrite!.content);
      expect(secondCardPanelWrite!.content).toBe(firstCardPanelWrite!.content);
      expect(secondIndexDiskContent).toBe(firstIndexDiskContent);
      expect(secondAppRootDiskContent).toBe(firstAppRootDiskContent);
      expect(secondCardPanelDiskContent).toBe(firstCardPanelDiskContent);
    });
  });

  it('fails with deterministic code when CEM source cannot be read', async () => {
    await withTempDir(async (tempDir) => {
      const config = createSingleProjectConfig(tempDir, true);

      await expect(
        generateFromConfig(config, { cwd: tempDir }),
      ).rejects.toMatchObject({
        code: 'QCE_CEM_READ_FAILED',
      });
      await expect(
        generateFromConfig(config, { cwd: tempDir }),
      ).rejects.toBeInstanceOf(GenerationError);
    });
  });

  it('falls back to CEM-only generation when adapter SSR is unavailable', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify({
          modules: [{ declarations: [{ tagName: 'app-root' }] }],
        }),
        'utf8',
      );
      await writeFile(
        path.join(tempDir, 'adapter-unsupported.mjs'),
        [
          'export async function probeSSR() {',
          '  return { available: false };',
          '}',
          '',
        ].join('\n'),
        'utf8',
      );

      const config = createSingleProjectConfig(tempDir, true);
      config.projects[0].adapterPackage = './adapter-unsupported.mjs';

      const result = await generateFromConfig(config, { cwd: tempDir });

      expect(result.projects[0].status).toBe('success');
      expect(result.projects[0].plannedWrites).toHaveLength(2);
      expect(result.projects[0].observedErrorCodes).toEqual([
        'QCE_SSR_UNSUPPORTED_FALLBACK',
      ]);
    });
  });

  it('loads the lit adapter SSR subpath package without fallback warning', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify({
          modules: [{ declarations: [{ tagName: 'lit-button' }] }],
        }),
        'utf8',
      );

      const config = createSingleProjectConfig(tempDir, true);
      config.projects[0].adapter = 'lit';
      config.projects[0].adapterPackage =
        '@qwik-custom-elements/adapter-lit/ssr';

      const result = await generateFromConfig(config, { cwd: tempDir });

      expect(result.projects[0].status).toBe('success');
      expect(result.projects[0].componentTags).toEqual(['lit-button']);
      expect(result.projects[0].observedErrorCodes).toEqual([]);
    });
  });

  it('fails with deterministic code when CEM shape is invalid', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify({ schemaVersion: '1.0.0' }),
        'utf8',
      );

      const config = createSingleProjectConfig(tempDir, true);

      await expect(
        generateFromConfig(config, { cwd: tempDir }),
      ).rejects.toMatchObject({
        code: 'QCE_CEM_INVALID_SHAPE',
        message:
          'CEM at ' +
          path.join(tempDir, 'custom-elements.json') +
          ' must include a "modules" array.',
      });
    });
  });

  it('fails when a module declarations field is not an array', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify({
          modules: [
            {
              declarations: 'not-an-array',
            },
          ],
        }),
        'utf8',
      );

      const config = createSingleProjectConfig(tempDir, true);

      await expect(
        generateFromConfig(config, { cwd: tempDir }),
      ).rejects.toMatchObject({
        code: 'QCE_CEM_INVALID_SHAPE',
        message:
          'CEM at ' +
          path.join(tempDir, 'custom-elements.json') +
          ' has invalid shape: modules[0].declarations must be an array when provided.',
      });
    });
  });

  it('fails when declaration tagName is present but not a non-empty string', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify({
          modules: [
            {
              declarations: [{ tagName: '   ' }],
            },
          ],
        }),
        'utf8',
      );

      const config = createSingleProjectConfig(tempDir, true);

      await expect(
        generateFromConfig(config, { cwd: tempDir }),
      ).rejects.toMatchObject({
        code: 'QCE_CEM_INVALID_SHAPE',
        message:
          'CEM at ' +
          path.join(tempDir, 'custom-elements.json') +
          ' has invalid shape: modules[0].declarations[0].tagName must be a non-empty string when provided.',
      });
    });
  });

  it('fails with deterministic diagnostics when targeted project id does not exist', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify({
          modules: [{ declarations: [{ tagName: 'app-root' }] }],
        }),
        'utf8',
      );

      const config = createSingleProjectConfig(tempDir, true);

      await expect(
        generateFromConfig(config, {
          cwd: tempDir,
          targetProjectIds: ['unknown-project'],
        }),
      ).rejects.toMatchObject({
        code: 'QCE_PROJECT_TARGET_UNKNOWN',
        message:
          'Unknown project id "unknown-project" requested via CLI targeting.',
      });
    });
  });

  it('executes multiple projects sequentially in deterministic id order', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements-a.json'),
        JSON.stringify({
          modules: [{ declarations: [{ tagName: 'alpha-card' }] }],
        }),
        'utf8',
      );
      await writeFile(
        path.join(tempDir, 'custom-elements-z.json'),
        JSON.stringify({
          modules: [{ declarations: [{ tagName: 'zeta-card' }] }],
        }),
        'utf8',
      );

      const config: GeneratorConfig = {
        dryRun: true,
        projects: [
          {
            id: 'z-project',
            adapter: 'stencil',
            adapterPackage: '@qwik-custom-elements/adapter-stencil',
            source: './custom-elements-z.json',
            outDir: './src/generated/z',
          },
          {
            id: 'a-project',
            adapter: 'stencil',
            adapterPackage: '@qwik-custom-elements/adapter-stencil',
            source: './custom-elements-a.json',
            outDir: './src/generated/a',
          },
        ],
      };

      const result = await generateFromConfig(config, { cwd: tempDir });

      expect(result.projects.map((project) => project.projectId)).toEqual([
        'a-project',
        'z-project',
      ]);
      expect(result.projects[0].componentTags).toEqual(['alpha-card']);
      expect(result.projects[1].componentTags).toEqual(['zeta-card']);
    });
  });

  it('executes multiple projects in parallel mode with deterministic id ordering', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements-a.json'),
        JSON.stringify({
          modules: [{ declarations: [{ tagName: 'alpha-card' }] }],
        }),
        'utf8',
      );
      await writeFile(
        path.join(tempDir, 'custom-elements-z.json'),
        JSON.stringify({
          modules: [{ declarations: [{ tagName: 'zeta-card' }] }],
        }),
        'utf8',
      );

      const config: GeneratorConfig = {
        dryRun: true,
        parallel: true,
        projects: [
          {
            id: 'z-project',
            adapter: 'stencil',
            adapterPackage: '@qwik-custom-elements/adapter-stencil',
            source: './custom-elements-z.json',
            outDir: './src/generated/z',
          },
          {
            id: 'a-project',
            adapter: 'stencil',
            adapterPackage: '@qwik-custom-elements/adapter-stencil',
            source: './custom-elements-a.json',
            outDir: './src/generated/a',
          },
        ],
      };

      const result = await generateFromConfig(config, { cwd: tempDir });

      expect(result.projects.map((project) => project.projectId)).toEqual([
        'a-project',
        'z-project',
      ]);
      expect(result.projects[0].componentTags).toEqual(['alpha-card']);
      expect(result.projects[1].componentTags).toEqual(['zeta-card']);
    });
  });

  it('aggregates all project failures in parallel mode', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements-valid.json'),
        JSON.stringify({
          modules: [{ declarations: [{ tagName: 'alpha-card' }] }],
        }),
        'utf8',
      );

      const config: GeneratorConfig = {
        dryRun: true,
        parallel: true,
        projects: [
          {
            id: 'b-missing-project',
            adapter: 'stencil',
            adapterPackage: '@qwik-custom-elements/adapter-stencil',
            source: './custom-elements-missing-b.json',
            outDir: './src/generated/b',
          },
          {
            id: 'a-valid-project',
            adapter: 'stencil',
            adapterPackage: '@qwik-custom-elements/adapter-stencil',
            source: './custom-elements-valid.json',
            outDir: './src/generated/a',
          },
          {
            id: 'c-missing-project',
            adapter: 'stencil',
            adapterPackage: '@qwik-custom-elements/adapter-stencil',
            source: './custom-elements-missing-c.json',
            outDir: './src/generated/c',
          },
        ],
      };

      await expect(
        generateFromConfig(config, { cwd: tempDir }),
      ).rejects.toMatchObject({
        code: 'QCE_PARALLEL_PROJECT_FAILURES',
        message: expect.stringContaining('b-missing-project'),
      });
      await expect(
        generateFromConfig(config, { cwd: tempDir }),
      ).rejects.toMatchObject({
        message: expect.stringContaining('c-missing-project'),
      });
      await expect(
        generateFromConfig(config, { cwd: tempDir }),
      ).rejects.toMatchObject({
        message: expect.stringContaining('QCE_CEM_READ_FAILED'),
      });
    });
  });

  it('rejects output paths that resolve outside the workspace root', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify({
          modules: [{ declarations: [{ tagName: 'app-root' }] }],
        }),
        'utf8',
      );

      const config = createSingleProjectConfig(tempDir, true);
      config.projects[0].outDir = '../outside-generated';

      await expect(
        generateFromConfig(config, { cwd: tempDir }),
      ).rejects.toMatchObject({
        code: 'QCE_OUTPUT_OUTSIDE_WORKSPACE',
        message:
          'Project "demo" output path resolves outside workspace root: ../outside-generated',
      });
    });
  });

  it('fails when multiple projects resolve to the same output directory', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify({
          modules: [{ declarations: [{ tagName: 'app-root' }] }],
        }),
        'utf8',
      );

      const config: GeneratorConfig = {
        dryRun: true,
        projects: [
          {
            id: 'a-project',
            adapter: 'stencil',
            adapterPackage: '@qwik-custom-elements/adapter-stencil',
            source: './custom-elements.json',
            outDir: './src/generated',
          },
          {
            id: 'b-project',
            adapter: 'stencil',
            adapterPackage: '@qwik-custom-elements/adapter-stencil',
            source: './custom-elements.json',
            outDir: './src/../src/generated',
          },
        ],
      };

      await expect(
        generateFromConfig(config, { cwd: tempDir }),
      ).rejects.toMatchObject({
        code: 'QCE_OUTPUT_PATH_COLLISION',
        message:
          'Projects "a-project" and "b-project" resolve to the same output directory: ' +
          path.resolve(tempDir, 'src/generated'),
      });
    });
  });
});
