import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import { GenerationError, generateFromConfig } from '../generator.js';
import type { GeneratorConfig } from '../types.js';

async function withTempDir(
  run: (tempDir: string) => Promise<void>,
): Promise<void> {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'qce-core-'));
  try {
    await run(tempDir);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

function createSingleProjectConfig(tempDir: string, dryRun = false): GeneratorConfig {
  return {
    dryRun,
    projects: [
      {
        id: 'demo',
        adapter: 'stencil',
        adapterPackage: '@qwik-custom-elements/adapter-stencil',
        source: './custom-elements.json',
        outDir: './src/generated',
      },
    ],
  };
}

describe('generateFromConfig', () => {
  it('produces deterministic planned writes in dry-run mode without mutating files', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify(
          {
            modules: [
              {
                declarations: [
                  { tagName: 'z-card' },
                  { tagName: 'a-button' },
                  { tagName: 'z-card' },
                ],
              },
            ],
          },
          null,
          2,
        ),
        'utf8',
      );

      const result = await generateFromConfig(
        createSingleProjectConfig(tempDir, true),
        { cwd: tempDir },
      );

      expect(result.dryRun).toBe(true);
      expect(result.projects).toHaveLength(1);
      expect(result.projects[0].wroteFiles).toBe(false);
      expect(result.projects[0].componentTags).toEqual(['a-button', 'z-card']);

      const [plannedWrite] = result.projects[0].plannedWrites;
      expect(plannedWrite.content).toContain(
        '// Generated by @qwik-custom-elements/core. Project: demo.',
      );
      expect(plannedWrite.content).toContain(
        'export const generatedComponentTags = ["a-button","z-card"] as const;',
      );

      await expect(readFile(plannedWrite.path, 'utf8')).rejects.toThrow();
    });
  });

  it('writes generated index.ts in non-dry-run mode', async () => {
    await withTempDir(async (tempDir) => {
      await writeFile(
        path.join(tempDir, 'custom-elements.json'),
        JSON.stringify({ modules: [{ declarations: [{ tagName: 'app-root' }] }] }),
        'utf8',
      );

      const result = await generateFromConfig(createSingleProjectConfig(tempDir), {
        cwd: tempDir,
      });
      const [plannedWrite] = result.projects[0].plannedWrites;
      const diskContent = await readFile(plannedWrite.path, 'utf8');

      expect(result.projects[0].wroteFiles).toBe(true);
      expect(diskContent).toBe(plannedWrite.content);
    });
  });

  it('fails with deterministic code when CEM source cannot be read', async () => {
    await withTempDir(async (tempDir) => {
      const config = createSingleProjectConfig(tempDir, true);

      await expect(generateFromConfig(config, { cwd: tempDir })).rejects.toMatchObject(
        {
          code: 'QCE_CEM_READ_FAILED',
        },
      );
      await expect(generateFromConfig(config, { cwd: tempDir })).rejects.toBeInstanceOf(
        GenerationError,
      );
    });
  });
});
